version: '3.3'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: textsummarizer
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: summarizer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U textsummarizer"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://textsummarizer:${DB_PASSWORD:-password123}@postgres:5432/summarizer_db
      - SESSION_SECRET=${SESSION_SECRET:-dev_session_secret_change_in_production}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: