version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: textsummarizer
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: summarizer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://textsummarizer:password123@postgres:5432/summarizer_db
      - SESSION_SECRET=dev_session_secret_change_in_production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run dev

volumes:
  postgres_data: