# docker-compose.yml
version: '3.8'

services:
  backend:
    build: ./BackEnd
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=summarization_db
      - REDIS_HOST=redis
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mongodb_data: